[package]
name = "Oracle"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
SupraOracle = { local = "../supra-svalue-feed-framework" }

[addresses]
oracle =  "0x0"
sui =  "0000000000000000000000000000000000000000000000000000000000000002"
